blank_issues_enabled: false
contact_links:
  - name: Start a discussion
    about: 🗨 Have an idea or suggestion which requires discussions? - Let use Teams for that.
    url: https://teams.microsoft.com/l/channel/19%3ae7d7244bc29c4b39905d68e900212524%40thread.tacv2/General?groupId=18f1b199-63c3-4547-abe1-04f46ee8b40a&tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47